# Generated by Django 3.0.6 on 2020-05-15 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timiolarryscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='status_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='scrumygoal',
            name='created_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumygoal',
            name='goal_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumygoal',
            name='moved_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumygoal',
            name='owner',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumygoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='created_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='moved_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='moved_from',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='moved_to',
            field=models.CharField(default='', max_length=50),
        ),
    ]
