# Generated by Django 3.0.6 on 2020-05-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timiolarryscrumy', '0003_auto_20200516_0257'),
        ('timiolarryscrumy', '0003_auto_20200515_1704'),
    ]

    operations = [
    ]
